[package]
version = "0.1.0"
name = "blowfish-compat"
authors = ["fzzr <a@koz.email>"]
description = "Blowfish-compat implementation."
edition = "2018"

[dependencies]
blowfish = "0.3.0"
bswap = { version = "0.4.0", optional = true}
